version: '3'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
        - ./src:/var/www/html
    environment:
      DB_DATABASE: /var/www/html/database/database.sqlite
    ports:
        - "9000:9000"
    networks:
      - laravel


